// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirPath() {
  return window['go']['main']['App']['GetDirPath']();
}

export function GetFileName() {
  return window['go']['main']['App']['GetFileName']();
}

export function GetTasksProgress(arg1) {
  return window['go']['main']['App']['GetTasksProgress'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}
