// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dl} from '../models';

export function GetDirPath():Promise<string>;

export function GetFileName():Promise<string>;

export function GetTasksProgress(arg1:Array<string>):Promise<Array<dl.TaskProgress>>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function PauseTask(arg1:string):Promise<void>;

export function RemoveTask(arg1:string):Promise<void>;

export function StartTask(arg1:string,arg2:string):Promise<void>;
